# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38d42435015aca39d8c4620404f704a79b819bb8bad05f9b02fb1a0a8bf32d4485918b155c492a86fd3d8b3b353788194bff7b6316839552c8e420413a2597a9

test:
  secret_key_base: bbd5b92f6b487c57dbd1bfce36011d5cbfa9ed025351ece67b4fa8e92b904bb57e4d9bfd91e6a1866f91ed047632d51979549a15630e98b7c54863fe6498515e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
